In [1]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, __у кого__ списали) не могут получить за него больше 0 баллов.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу курса XXX выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [250]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [251]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [252]:
# Записать ответ в переменную num_studs
num_studs = np.shape(marks)[0]

In [253]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [254]:
# Записать ответ в переменную max_mark
max_mark = marks.max(axis=0)[0]

In [255]:
print(max_mark)

7.0


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [256]:
marks = marks.T

In [257]:
marks[0] = (marks[0] / max_mark) * 10

In [258]:
marks = marks.T
marks[:3]

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ]])

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [259]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = np.array([0.3, 0.4, 0.3])

In [260]:
tests = marks[:, 0:3]
hw = marks[:, 3:6]
coll = marks[:, 6:]

In [261]:
tests = (np.sum(tests, axis=1)) / 3
hw = (np.sum(hw, axis=1)) / 3

In [262]:
tests = tests[:, np.newaxis]
hw = hw[:, np.newaxis]
nakop = np.hstack((np.hstack((tests, hw)), coll))
nakop = np.dot(nakop, weights[:, np.newaxis])
nakop[:4]
marks = np.hstack((marks, nakop))
marks[:3]

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ,  3.53      ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ,  3.53      ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ,  8.23857143]])

### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [263]:
np.sum([True, False, True]) # 2 значения True

2

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [264]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


In [265]:
zeros = np.zeros((np.shape(marks)[0], 1), dtype = float)

In [266]:
zeros = marks[:, -1][:, np.newaxis] == zeros

In [267]:
print(np.sum(zeros))

3


### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [268]:
sevens = np.full((np.shape(marks)[0], 1), 7, dtype = float)

In [269]:
sevens = marks[:, -1][:, np.newaxis] > sevens

In [270]:
marks = np.hstack((marks, sevens))
print(marks[:, 8])

[0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 1. 1.]


### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.sort) и взять первую половину.

In [271]:
automats = marks[marks[:,7].argsort()]

In [272]:
automats = automats[::-1]

In [273]:
automats = automats[:14]
print(automats)

[[10.         10.         10.          9.7        10.         10.
  10.          9.96        1.        ]
 [ 9.28571429  8.7         9.5        10.5         9.8        10.
  10.          9.78857143  1.        ]
 [10.          9.7        10.          8.1        10.         10.
   9.5         9.56666667  1.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905  1.        ]
 [ 5.71428571 10.         10.          9.9         9.7        10.
   9.          9.21809524  1.        ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2         1.        ]
 [ 4.28571429  8.7        10.          9.4        10.7        10.
   9.          9.01190476  1.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952  1.        ]
 [ 5.          9.3        10.          9.9        10.         10.
   8.          8.81666667  1.        ]
 [ 8.57142857  5.         10.          9.7        10. 

### Сложность заданий (1.5 балла)
Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами.
Пример, что имеется в виду: если есть 4 студента с весами [0.1, 0.2, 0.3, 0.4] и оценками [3, 7, 9, 10], то средняя оценка за задание с весами получится 

In [246]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [274]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))

# разделите веса на их сумму, чтобы они суммировались к 1
weights = weights / np.sum(weights)
print(weights)

[0.01315789 0.01315789 0.01315789 0.01315789 0.01315789 0.01315789
 0.01315789 0.02631579 0.02631579 0.02631579 0.02631579 0.03947368
 0.03947368 0.03947368 0.03947368 0.03947368 0.03947368 0.03947368
 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158
 0.05263158 0.05263158 0.05263158 0.05263158]


Посчитайте указанным образом сложность каждого "столбца".

In [275]:
firstT = np.dot(marks[:, 0], weights[:, np.newaxis])
print(firstT)

[4.90037594]


In [276]:
secondT = np.dot(marks[:, 1], weights[:, np.newaxis])
print(secondT)

[7.11973684]


In [277]:
thirdT = np.dot(marks[:, 2], weights[:, np.newaxis])
print(thirdT)

[7.85789474]


In [278]:
coll = np.dot(marks[:, 6], weights[:, np.newaxis])
print(coll)

[4.87368421]
